[versions]
"21.07" = { created_at = 2022-03-18T11:00:00.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/21.07" }
"22.00" = { created_at = 2023-12-17T09:16:52.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/22.00" }
"22.01" = { created_at = 2023-12-17T09:48:49.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/22.01" }
"23.01" = { created_at = 2023-12-17T10:22:53.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/23.01" }
"24.05" = { created_at = 2024-05-15T19:12:58.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/24.05" }
"24.06" = { created_at = 2024-05-27T07:50:07.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/24.06" }
"24.07" = { created_at = 2024-06-19T10:45:51.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/24.07" }
"24.08" = { created_at = 2024-08-12T12:01:23.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/24.08" }
"24.09" = { created_at = 2024-11-30T10:45:19.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/24.09" }
"25.00" = { created_at = 2025-07-05T14:34:51.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/25.00" }
"25.01" = { created_at = 2025-08-03T11:18:58.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/25.01" }
"26.00" = { created_at = 2026-02-12T12:45:13.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/26.00" }
"26.01" = { created_at = 2026-04-27T16:39:51.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/26.01" }
"26.02" = { created_at = 2026-06-26T06:10:10.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/26.02" }
"26.03" = { created_at = 2026-09-04T07:34:42.000Z, release_url = "https://github.com/ip7z/7zip/releases/tag/26.03" }
