[versions]
"1.0.0-beta.1" = { created_at = 2026-04-18T20:32:16.000Z, release_url = "https://github.com/endevco/aube/releases/tag/v1.0.0-beta.1" }
"1.0.0-beta.2" = { created_at = 2026-04-18T21:28:00.000Z, release_url = "https://github.com/endevco/aube/releases/tag/v1.0.0-beta.2" }
"1.0.0-beta.3" = { created_at = 2026-04-19T02:24:22.000Z, release_url = "https://github.com/endevco/aube/releases/tag/v1.0.0-beta.3" }
"1.0.0-beta.4" = { created_at = 2026-04-19T04:36:26.000Z, release_url = "https://github.com/endevco/aube/releases/tag/v1.0.0-beta.4" }
