[versions]
"0.1.1" = { created_at = 2020-06-03T18:10:54.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.1.1" }
"0.1.2" = { created_at = 2020-06-28T16:10:37.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.1.2" }
"0.2.0" = { created_at = 2020-07-01T10:38:55.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.2.0" }
"0.3.0" = { created_at = 2020-07-05T19:39:41.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.3.0" }
"0.4.0" = { created_at = 2020-08-03T17:04:55.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.4.0" }
"0.5.0" = { created_at = 2020-08-21T10:10:53.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.5.0" }
"0.5.1" = { created_at = 2020-08-26T15:28:47.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.5.1" }
"0.6.0" = { created_at = 2020-11-21T19:51:52.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.6.0" }
"0.6.1" = { created_at = 2020-12-20T16:02:05.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.6.1" }
"0.7.0" = { created_at = 2020-12-21T10:12:45.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.7.0" }
"0.8.0" = { created_at = 2020-12-29T22:00:59.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.8.0" }
"0.8.1" = { created_at = 2021-01-02T13:27:03.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.8.1" }
"0.8.2" = { created_at = 2021-02-18T19:30:47.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.8.2" }
"0.8.3" = { created_at = 2021-02-21T12:49:08.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.8.3" }
"0.9.0" = { created_at = 2021-03-06T15:21:27.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.9.0" }
"0.9.1" = { created_at = 2021-03-06T18:34:48.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.9.1" }
"0.10.0" = { created_at = 2021-04-16T20:47:16.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.10.0" }
"0.11.0" = { created_at = 2021-06-13T18:39:16.000Z, release_url = "https://github.com/jckuester/awsls/releases/tag/v0.11.0" }
