[versions]
"0.1.0" = { created_at = 2017-11-22T08:49:08.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.1.0" }
"0.2.0" = { created_at = 2018-05-10T10:51:17.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.2.0" }
"0.3.0" = { created_at = 2018-11-19T20:25:03.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.3.0" }
"0.3.1" = { created_at = 2018-11-25T18:31:47.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.3.1" }
"0.3.2" = { created_at = 2018-12-16T21:13:29.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.3.2" }
"0.4.0" = { created_at = 2019-09-13T18:24:06.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.4.0" }
"0.4.1" = { created_at = 2019-11-19T20:35:52.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.4.1" }
"0.5.0" = { created_at = 2020-02-24T19:40:16.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.5.0" }
"0.6.0" = { created_at = 2020-03-06T17:38:34.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.6.0" }
"0.7.0" = { created_at = 2020-04-22T17:35:24.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.7.0" }
"0.8.0" = { created_at = 2020-05-11T20:51:48.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2020-05-25T17:41:45.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.9.0" }
"0.10.0" = { created_at = 2020-06-10T07:47:42.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.10.0" }
"0.10.1" = { created_at = 2020-06-30T12:16:13.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.10.1" }
"0.10.2" = { created_at = 2020-09-07T10:36:59.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.10.2" }
"0.11.0" = { created_at = 2020-12-31T13:12:09.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.11.0" }
"0.11.1" = { created_at = 2021-01-03T13:03:28.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.11.1" }
"0.12.0" = { created_at = 2022-02-08T23:06:24.000Z, release_url = "https://github.com/jckuester/awsweeper/releases/tag/v0.12.0" }
