[versions]
"2025.12.0" = { created_at = 2025-12-05T21:39:33.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2025.12.0" }
"2025.12.1" = { created_at = 2026-01-07T19:48:19.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2025.12.1" }
"2026.1.0" = { created_at = 2026-02-02T09:34:46.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2026.1.0" }
"2026.2.0" = { created_at = 2026-03-02T17:39:37.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2026.2.0" }
"2026.3.0" = { created_at = 2026-03-27T19:20:46.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2026.3.0" }
"2026.4.1" = { created_at = 2026-04-23T14:11:09.000Z, release_url = "https://github.com/bitwarden/clients/releases/tag/cli-v2026.4.1" }
