[versions]
"22.12.0" = { created_at = 2022-12-09T15:49:43.000Z, release_url = "https://github.com/psf/black/releases/tag/22.12.0" }
"23.1.0" = { created_at = 2023-02-01T02:47:11.000Z, release_url = "https://github.com/psf/black/releases/tag/23.1.0" }
"23.3.0" = { created_at = 2023-03-29T00:53:23.000Z, release_url = "https://github.com/psf/black/releases/tag/23.3.0" }
"23.7.0" = { created_at = 2023-07-11T00:09:47.000Z, release_url = "https://github.com/psf/black/releases/tag/23.7.0" }
"23.9.0" = { created_at = 2023-09-09T03:24:49.000Z, release_url = "https://github.com/psf/black/releases/tag/23.9.0" }
"23.9.1" = { created_at = 2023-09-11T00:35:41.000Z, release_url = "https://github.com/psf/black/releases/tag/23.9.1" }
"23.10.0" = { created_at = 2023-10-17T14:22:24.000Z, release_url = "https://github.com/psf/black/releases/tag/23.10.0" }
"23.10.1" = { created_at = 2023-10-23T17:59:16.000Z, release_url = "https://github.com/psf/black/releases/tag/23.10.1" }
"23.11.0" = { created_at = 2023-11-08T04:44:46.000Z, release_url = "https://github.com/psf/black/releases/tag/23.11.0" }
"23.12.0" = { created_at = 2023-12-12T05:55:28.000Z, release_url = "https://github.com/psf/black/releases/tag/23.12.0" }
"23.12.1" = { created_at = 2023-12-22T23:04:32.000Z, release_url = "https://github.com/psf/black/releases/tag/23.12.1" }
"24.1.0" = { created_at = 2024-01-26T04:35:21.000Z, release_url = "https://github.com/psf/black/releases/tag/24.1.0" }
"24.1.1" = { created_at = 2024-01-28T04:51:32.000Z, release_url = "https://github.com/psf/black/releases/tag/24.1.1" }
"24.2.0" = { created_at = 2024-02-12T20:11:15.000Z, release_url = "https://github.com/psf/black/releases/tag/24.2.0" }
"24.3.0" = { created_at = 2024-03-15T19:17:00.000Z, release_url = "https://github.com/psf/black/releases/tag/24.3.0" }
"24.4.0" = { created_at = 2024-04-12T20:12:22.000Z, release_url = "https://github.com/psf/black/releases/tag/24.4.0" }
"24.4.1" = { created_at = 2024-04-24T14:23:25.000Z, release_url = "https://github.com/psf/black/releases/tag/24.4.1" }
"24.4.2" = { created_at = 2024-04-25T23:52:26.000Z, release_url = "https://github.com/psf/black/releases/tag/24.4.2" }
"24.8.0" = { created_at = 2024-08-02T16:38:22.000Z, release_url = "https://github.com/psf/black/releases/tag/24.8.0" }
"24.10.0" = { created_at = 2024-10-07T18:43:01.000Z, release_url = "https://github.com/psf/black/releases/tag/24.10.0" }
"25.1.0" = { created_at = 2025-01-29T02:34:41.000Z, release_url = "https://github.com/psf/black/releases/tag/25.1.0" }
"25.9.0" = { created_at = 2025-09-18T23:39:02.000Z, release_url = "https://github.com/psf/black/releases/tag/25.9.0" }
"25.11.0" = { created_at = 2025-11-10T01:43:38.000Z, release_url = "https://github.com/psf/black/releases/tag/25.11.0" }
"25.12.0" = { created_at = 2025-12-08T01:39:14.000Z, release_url = "https://github.com/psf/black/releases/tag/25.12.0" }
"26.1.0" = { created_at = 2026-01-18T04:30:36.000Z, release_url = "https://github.com/psf/black/releases/tag/26.1.0" }
"26.3.0" = { created_at = 2026-03-06T17:30:53.000Z, release_url = "https://github.com/psf/black/releases/tag/26.3.0" }
"26.3.1" = { created_at = 2026-03-12T03:08:43.000Z, release_url = "https://github.com/psf/black/releases/tag/26.3.1" }
