[versions]
"2.3.0" = { created_at = 2026-05-21T18:16:15.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.3.0" }
"2.3.1" = { created_at = 2026-05-22T19:59:12.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.3.1" }
"2.3.2" = { created_at = 2026-06-09T16:51:27.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.3.2" }
"2.3.3" = { created_at = 2026-06-22T17:32:52.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.3.3" }
"2.3.4" = { created_at = 2026-07-23T14:12:29.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.3.4" }
"2.4.0" = { created_at = 2026-08-20T14:42:33.000Z, release_url = "https://github.com/crossplane/crossplane/releases/tag/v2.4.0" }
"2.4.1" = { created_at = 2026-08-25T21:41:00.998Z }
"2.5.0" = { created_at = 2026-08-25T21:41:00.998Z }
