[versions]
"2.100.3" = { created_at = 2025-09-10T11:08:37.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.3" }
"2.100.4" = { created_at = 2025-09-10T12:30:41.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.4" }
"2.100.5" = { created_at = 2025-09-10T13:47:14.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.5" }
"2.100.6" = { created_at = 2025-09-11T18:19:56.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.6" }
"2.100.7" = { created_at = 2025-09-17T20:01:54.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.7" }
"2.100.8" = { created_at = 2025-09-17T23:49:52.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.8" }
"2.100.9" = { created_at = 2025-10-15T13:41:24.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.9" }
"2.100.10" = { created_at = 2025-10-27T09:54:37.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.10" }
"2.100.11" = { created_at = 2025-10-27T17:48:53.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.11" }
"2.100.12" = { created_at = 2025-10-31T22:25:41.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.12" }
"2.100.13" = { created_at = 2025-12-17T22:19:18.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.13" }
"2.100.14" = { created_at = 2025-12-18T12:32:34.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.100.14" }
"2.101.0" = { created_at = 2026-01-15T11:56:11.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.0" }
"2.101.1" = { created_at = 2026-01-16T10:13:48.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.1" }
"2.101.2" = { created_at = 2026-02-04T14:40:55.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.2" }
"2.101.3" = { created_at = 2026-02-04T14:58:53.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.3" }
"2.101.4" = { created_at = 2026-02-13T08:54:46.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.4" }
"2.101.5" = { created_at = 2026-02-13T10:58:59.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.5" }
"2.101.6" = { created_at = 2026-02-13T11:09:08.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.6" }
"2.101.7" = { created_at = 2026-02-13T15:08:52.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.7" }
"2.101.8" = { created_at = 2026-02-19T01:34:34.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.8" }
"2.101.9" = { created_at = 2026-02-22T21:09:40.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.9" }
"2.101.10" = { created_at = 2026-02-23T19:17:10.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.10" }
"2.101.11" = { created_at = 2026-02-24T06:51:58.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.11" }
"2.101.12" = { created_at = 2026-02-25T10:05:57.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.12" }
"2.101.13" = { created_at = 2026-02-25T15:02:13.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.13" }
"2.101.14" = { created_at = 2026-03-06T15:32:28.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.14" }
"2.101.15" = { created_at = 2026-03-10T15:06:02.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.15" }
"2.101.16" = { created_at = 2026-03-12T11:48:34.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.16" }
"2.101.17" = { created_at = 2026-03-12T14:43:43.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.17" }
"2.101.18" = { created_at = 2026-03-12T18:02:33.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.18" }
"2.101.19" = { created_at = 2026-03-13T13:12:06.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.19" }
"2.101.20" = { created_at = 2026-03-16T18:50:54.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.20" }
"2.101.21" = { created_at = 2026-03-16T22:23:31.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.21" }
"2.101.22" = { created_at = 2026-03-19T11:41:21.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.22" }
"2.101.23" = { created_at = 2026-03-19T18:47:30.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.23" }
"2.101.24" = { created_at = 2026-03-19T20:38:23.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.24" }
"2.101.25" = { created_at = 2026-03-19T21:05:30.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.25" }
"2.101.26" = { created_at = 2026-03-20T03:16:48.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.26" }
"2.101.27" = { created_at = 2026-03-20T19:50:24.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.27" }
"2.101.28" = { created_at = 2026-03-23T03:47:23.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.28" }
"2.101.29" = { created_at = 2026-03-23T16:16:04.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.29" }
"2.101.30" = { created_at = 2026-03-25T19:08:01.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.30" }
"2.101.31" = { created_at = 2026-03-25T20:25:29.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.31" }
"2.101.32" = { created_at = 2026-03-26T14:19:59.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.32" }
"2.101.33" = { created_at = 2026-03-27T23:24:26.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.33" }
"2.101.34" = { created_at = 2026-03-28T00:09:35.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.34" }
"2.101.35" = { created_at = 2026-03-28T05:51:05.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.35" }
"2.101.36" = { created_at = 2026-03-31T19:02:11.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.36" }
"2.101.37" = { created_at = 2026-04-02T16:02:48.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.37" }
"2.101.38" = { created_at = 2026-04-03T17:34:33.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.38" }
"2.101.39" = { created_at = 2026-04-07T19:24:15.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.39" }
"2.101.40" = { created_at = 2026-04-09T02:38:22.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.40" }
"2.101.41" = { created_at = 2026-04-10T18:57:50.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.41" }
"2.101.42" = { created_at = 2026-04-13T23:29:08.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.42" }
"2.101.43" = { created_at = 2026-04-15T23:05:18.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.43" }
"2.101.44" = { created_at = 2026-04-21T12:32:35.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.44" }
"2.101.45" = { created_at = 2026-04-21T18:45:01.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.45" }
"2.101.46" = { created_at = 2026-04-22T15:44:19.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.46" }
"2.101.47" = { created_at = 2026-04-24T17:20:59.000Z, release_url = "https://github.com/depot/cli/releases/tag/v2.101.47" }
