[versions]
"0.1.0" = { created_at = 2015-10-26T05:16:25.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.1.0" }
"0.1.1" = { created_at = 2015-10-26T16:42:23.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.1.1" }
"0.1.2" = { created_at = 2015-10-27T00:32:28.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.1.2" }
"0.2.0" = { created_at = 2015-11-03T14:20:34.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.2.0" }
"0.2.1" = { created_at = 2015-11-03T15:27:14.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.2.1" }
"0.3.1" = { created_at = 2015-11-18T05:17:26.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.3.1" }
"0.4.0" = { created_at = 2015-12-14T18:37:14.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.4.0" }
"0.4.1" = { created_at = 2016-02-06T21:40:56.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.4.1" }
"0.5.0" = { created_at = 2016-04-19T05:08:15.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.5.0" }
"0.5.1" = { created_at = 2016-05-15T15:19:18.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.5.1" }
"0.6.0" = { created_at = 2016-05-25T16:09:57.000Z, release_url = "https://github.com/jamesob/desk/releases/tag/v0.6.0" }
