[versions]
"0.21.0" = { created_at = 2022-02-28T08:02:28.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.21.0" }
"0.22.0" = { created_at = 2022-03-01T12:03:15.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.22.0" }
"0.23.0" = { created_at = 2022-03-09T12:46:40.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.23.0" }
"0.23.1" = { created_at = 2022-03-11T10:42:24.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.23.1" }
"0.23.2" = { created_at = 2022-03-17T12:08:07.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.23.2" }
"0.24.0" = { created_at = 2022-03-21T08:21:15.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.24.0" }
"0.25.0" = { created_at = 2022-03-23T11:38:30.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.25.0" }
"0.26.0" = { created_at = 2022-03-31T11:50:41.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.26.0" }
"0.27.0" = { created_at = 2022-04-08T09:13:21.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.27.0" }
"0.28.0" = { created_at = 2022-04-13T12:23:56.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.28.0" }
"0.28.1" = { created_at = 2022-04-15T10:12:14.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.28.1" }
"0.29.0" = { created_at = 2022-05-04T07:17:02.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.29.0" }
"0.30.0" = { created_at = 2022-05-13T12:01:55.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.30.0" }
"0.31.0" = { created_at = 2022-05-25T12:24:05.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.31.0" }
"0.31.1" = { created_at = 2022-05-31T08:34:52.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.31.1" }
"0.32.0" = { created_at = 2022-06-07T08:58:35.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.32.0" }
"0.32.1" = { created_at = 2022-06-07T12:33:58.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.32.1" }
"0.33.0" = { created_at = 2022-06-08T11:10:33.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.33.0" }
"0.34.0" = { created_at = 2022-06-16T12:58:26.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.34.0" }
"0.34.1" = { created_at = 2022-06-23T14:18:21.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.34.1" }
"0.35.0" = { created_at = 2022-07-06T12:46:56.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.35.0" }
"0.35.1" = { created_at = 2022-07-13T07:53:27.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.35.1" }
"0.35.2" = { created_at = 2022-07-19T14:58:16.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.35.2" }
"0.36.0" = { created_at = 2022-07-26T06:30:45.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.36.0" }
"0.37.0" = { created_at = 2022-08-11T13:00:26.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.37.0" }
"0.38.0" = { created_at = 2022-10-12T09:12:47.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.38.0" }
"0.38.1" = { created_at = 2022-10-13T15:22:08.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.38.1" }
"0.38.2" = { created_at = 2023-01-09T14:30:48.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.38.2" }
"0.39.0" = { created_at = 2023-06-06T11:47:55.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.39.0" }
"0.40.0" = { created_at = 2023-10-25T10:09:10.000Z, release_url = "https://github.com/snyk/driftctl/releases/tag/v0.40.0" }
