[versions]
"1.0.0" = { created_at = 2020-12-24T09:27:46.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.0.0" }
"1.1.0" = { created_at = 2020-12-26T23:21:06.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.1.0" }
"1.2.0" = { created_at = 2020-12-27T23:15:27.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.2.0" }
"1.2.1" = { created_at = 2020-12-28T15:23:31.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.2.1" }
"1.3.0" = { created_at = 2020-12-29T23:42:01.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.3.0" }
"1.4.0" = { created_at = 2020-12-30T00:02:24.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.4.0" }
"1.5.0" = { created_at = 2020-12-30T23:02:32.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.5.0" }
"1.5.1" = { created_at = 2020-12-31T23:17:17.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.5.1" }
"1.6.0" = { created_at = 2021-01-01T21:38:03.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.6.0" }
"1.7.1" = { created_at = 2021-01-02T20:44:02.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v1.7.1" }
"2.0.0" = { created_at = 2021-01-03T22:26:12.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v2.0.0" }
"2.1.0" = { created_at = 2021-01-05T00:05:53.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v2.1.0" }
"2.2.0" = { created_at = 2021-01-06T22:43:27.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v2.2.0" }
"2.3.0" = { created_at = 2021-01-12T22:19:27.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v2.3.0" }
"3.0.0" = { created_at = 2021-01-15T15:41:05.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v3.0.0" }
"4.0.0" = { created_at = 2021-01-18T12:42:43.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.0.0" }
"4.1.0" = { created_at = 2021-01-18T17:03:46.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.1.0" }
"4.2.0" = { created_at = 2021-01-20T20:39:40.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.2.0" }
"4.3.0" = { created_at = 2021-01-24T21:26:14.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.3.0" }
"4.3.1" = { created_at = 2021-01-26T21:09:29.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.3.1" }
"4.3.2" = { created_at = 2021-01-27T10:27:15.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.3.2" }
"4.3.3" = { created_at = 2021-01-29T13:50:11.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.3.3" }
"4.4.0" = { created_at = 2021-02-03T14:31:37.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.4.0" }
"4.4.1" = { created_at = 2021-02-05T13:06:55.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.4.1" }
"4.5.0" = { created_at = 2021-02-12T20:22:09.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.5.0" }
"4.6.0" = { created_at = 2021-02-14T22:59:21.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.0" }
"4.6.1" = { created_at = 2021-02-15T07:47:57.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.1" }
"4.6.2" = { created_at = 2021-02-16T19:42:55.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.2" }
"4.6.3" = { created_at = 2021-02-18T15:34:04.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.3" }
"4.6.4" = { created_at = 2021-02-22T17:31:14.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.4" }
"4.6.5" = { created_at = 2021-02-23T10:16:14.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.6.5" }
"4.7.0" = { created_at = 2021-03-02T23:26:05.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.7.0" }
"4.8.0" = { created_at = 2021-03-08T20:42:11.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.8.0" }
"4.8.1" = { created_at = 2021-03-19T08:58:51.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.8.1" }
"4.9.0" = { created_at = 2021-03-25T22:03:34.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.9.0" }
"4.9.1" = { created_at = 2021-03-27T20:56:29.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.9.1" }
"4.10.0" = { created_at = 2021-04-07T21:34:16.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.10.0" }
"4.10.1" = { created_at = 2021-04-14T20:46:08.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.10.1" }
"4.11.0" = { created_at = 2021-04-25T19:13:43.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.11.0" }
"4.11.1" = { created_at = 2021-04-28T08:50:01.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.11.1" }
"4.11.2" = { created_at = 2021-05-10T14:47:02.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v4.11.2" }
"5.0.0" = { created_at = 2021-05-22T14:04:35.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.0.0" }
"5.0.1" = { created_at = 2021-05-31T09:13:00.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.0.1" }
"5.1.0" = { created_at = 2021-06-07T20:36:31.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.1.0" }
"5.1.1" = { created_at = 2021-06-22T16:00:16.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.1.1" }
"5.2.0" = { created_at = 2021-07-09T10:27:09.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.2.0" }
"5.3.0" = { created_at = 2021-07-20T20:40:11.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.3.0" }
"5.4.0" = { created_at = 2021-07-23T20:18:30.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.4.0" }
"5.5.0" = { created_at = 2021-08-01T10:55:21.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.5.0" }
"5.6.0" = { created_at = 2021-08-19T22:58:15.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.6.0" }
"5.6.1" = { created_at = 2021-08-27T20:48:47.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.6.1" }
"5.6.2" = { created_at = 2021-08-27T22:37:07.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.6.2" }
"5.7.0" = { created_at = 2021-09-06T20:49:59.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.7.0" }
"5.8.0" = { created_at = 2021-09-23T11:44:37.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.8.0" }
"5.8.1" = { created_at = 2021-09-24T15:23:46.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.8.1" }
"5.9.0" = { created_at = 2021-10-22T22:30:20.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.9.0" }
"5.10.0" = { created_at = 2021-11-09T21:02:25.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.10.0" }
"5.10.1" = { created_at = 2021-11-23T14:30:09.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.10.1" }
"5.11.0" = { created_at = 2021-11-26T23:34:46.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.11.0" }
"5.12.0" = { created_at = 2021-12-03T20:11:37.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.12.0" }
"5.12.1" = { created_at = 2021-12-11T11:01:26.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.12.1" }
"5.13.0" = { created_at = 2022-01-29T15:36:26.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.13.0" }
"5.13.1" = { created_at = 2022-02-09T21:32:49.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.13.1" }
"5.13.2" = { created_at = 2022-02-18T19:08:31.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.13.2" }
"5.14.0" = { created_at = 2022-05-25T22:13:31.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.14.0" }
"5.15.0" = { created_at = 2022-08-02T22:28:47.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.15.0" }
"5.16.0" = { created_at = 2022-09-07T21:36:23.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.16.0" }
"5.17.0" = { created_at = 2022-09-10T23:38:14.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.17.0" }
"5.17.1" = { created_at = 2022-09-12T22:01:27.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.17.1" }
"5.18.0" = { created_at = 2022-09-18T08:15:48.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.18.0" }
"5.18.1" = { created_at = 2022-09-18T13:56:56.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.18.1" }
"5.19.0" = { created_at = 2022-09-27T21:34:13.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.19.0" }
"5.20.0" = { created_at = 2022-10-22T20:58:45.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.20.0" }
"5.21.0" = { created_at = 2023-01-04T20:39:15.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.21.0" }
"5.21.1" = { created_at = 2023-01-06T21:06:31.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.21.1" }
"5.22.0" = { created_at = 2023-02-05T23:22:06.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.22.0" }
"5.23.0" = { created_at = 2023-04-08T21:51:53.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.23.0" }
"5.24.0" = { created_at = 2023-05-31T22:08:05.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.24.0" }
"5.25.0" = { created_at = 2023-06-06T13:15:28.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.25.0" }
"5.26.0" = { created_at = 2024-02-12T20:02:16.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.26.0" }
"5.27.0" = { created_at = 2024-02-18T13:28:17.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.27.0" }
"5.28.0" = { created_at = 2024-04-21T10:13:08.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.28.0" }
"5.29.0" = { created_at = 2024-06-17T10:32:03.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.29.0" }
"5.30.0" = { created_at = 2024-12-30T20:57:15.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.30.0" }
"5.30.1" = { created_at = 2024-12-30T21:26:12.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.30.1" }
"5.31.0" = { created_at = 2025-06-06T10:52:50.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.31.0" }
"5.32.0" = { created_at = 2025-11-22T11:21:12.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.32.0" }
"5.33.0" = { created_at = 2026-02-13T23:12:43.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.33.0" }
"5.34.0" = { created_at = 2026-03-09T20:30:39.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.34.0" }
"5.34.1" = { created_at = 2026-03-20T10:03:16.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.34.1" }
"5.34.2" = { created_at = 2026-03-20T23:35:33.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.34.2" }
"5.35.0" = { created_at = 2026-03-31T09:21:37.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.35.0" }
"5.36.0" = { created_at = 2026-04-27T22:31:42.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.36.0" }
"5.36.1" = { created_at = 2026-04-29T22:00:38.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.36.1" }
"5.37.0" = { created_at = 2026-08-18T08:48:32.000Z, release_url = "https://github.com/dundee/gdu/releases/tag/v5.37.0" }
