[versions]
"0.1.4" = { created_at = 2025-02-16T00:58:17.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.4" }
"0.1.5" = { created_at = 2025-02-16T21:15:12.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.5" }
"0.1.6" = { created_at = 2025-02-16T21:29:45.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.6" }
"0.1.7" = { created_at = 2025-02-16T22:49:37.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.7" }
"0.1.8" = { created_at = 2025-02-16T23:23:49.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.8" }
"0.1.9" = { created_at = 2025-02-17T13:41:24.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.1.9" }
"0.2.0" = { created_at = 2025-02-17T15:40:03.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.2.0" }
"0.2.1" = { created_at = 2025-02-17T18:36:30.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.2.1" }
"0.2.2" = { created_at = 2025-02-17T19:00:34.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.2.2" }
"0.2.3" = { created_at = 2025-02-17T22:34:14.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.2.3" }
"0.2.4" = { created_at = 2025-02-18T14:31:31.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.2.4" }
"0.3.0" = { created_at = 2025-02-19T15:38:34.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.3.0" }
"0.3.1" = { created_at = 2025-02-19T15:53:25.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.3.1" }
"0.3.2" = { created_at = 2025-02-19T15:58:41.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.3.2" }
"0.3.3" = { created_at = 2025-02-19T16:19:59.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.3.3" }
"0.4.0" = { created_at = 2025-02-20T01:00:26.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.0" }
"0.4.1" = { created_at = 2025-02-20T01:17:13.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.1" }
"0.4.2" = { created_at = 2025-02-21T02:01:18.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.2" }
"0.4.3" = { created_at = 2025-02-21T15:51:05.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.3" }
"0.4.4" = { created_at = 2025-02-22T14:09:32.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.4" }
"0.4.5" = { created_at = 2025-02-23T19:45:18.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.5" }
"0.4.6" = { created_at = 2025-02-24T14:57:00.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.4.6" }
"0.5.0" = { created_at = 2025-02-25T01:36:01.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.5.0" }
"0.5.1" = { created_at = 2025-03-20T15:30:03.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.5.1" }
"0.6.0" = { created_at = 2025-03-21T14:26:26.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.0" }
"0.6.1" = { created_at = 2025-03-22T13:38:00.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.1" }
"0.6.2" = { created_at = 2025-03-24T22:05:44.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.2" }
"0.6.3" = { created_at = 2025-03-29T19:06:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.3" }
"0.6.4" = { created_at = 2025-03-29T20:48:56.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.4" }
"0.6.5" = { created_at = 2025-03-30T17:18:48.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.6.5" }
"0.7.0" = { created_at = 2025-04-04T14:40:53.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.0" }
"0.7.1" = { created_at = 2025-04-09T23:58:20.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.1" }
"0.7.2" = { created_at = 2025-04-10T16:25:21.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.2" }
"0.7.3" = { created_at = 2025-04-10T18:19:45.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.3" }
"0.7.4" = { created_at = 2025-04-11T15:42:19.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.4" }
"0.7.5" = { created_at = 2025-04-11T16:53:28.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.7.5" }
"0.8.0" = { created_at = 2025-04-17T23:42:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.0" }
"0.8.1" = { created_at = 2025-04-18T00:35:15.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.1" }
"0.8.2" = { created_at = 2025-04-18T00:41:43.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.2" }
"0.8.3" = { created_at = 2025-04-22T17:57:31.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.3" }
"0.8.4" = { created_at = 2025-04-23T16:37:34.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.4" }
"0.8.5" = { created_at = 2025-04-23T16:55:28.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v0.8.5" }
"1.0.0" = { created_at = 2025-04-26T16:12:18.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.0.0" }
"1.1.0" = { created_at = 2025-05-14T20:03:01.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.1.0" }
"1.1.1" = { created_at = 2025-05-16T17:14:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.1.1" }
"1.1.2" = { created_at = 2025-05-25T15:55:05.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.1.2" }
"1.2.0" = { created_at = 2025-06-13T17:20:05.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.2.0" }
"1.2.1" = { created_at = 2025-07-09T14:06:21.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.2.1" }
"1.2.2" = { created_at = 2025-07-21T18:08:56.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.2.2" }
"1.3.0" = { created_at = 2025-08-12T13:53:58.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.3.0" }
"1.4.0" = { created_at = 2025-08-12T17:50:25.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.4.0" }
"1.5.0" = { created_at = 2025-08-14T01:28:21.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.5.0" }
"1.6.0" = { created_at = 2025-08-16T23:47:42.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.6.0" }
"1.7.0" = { created_at = 2025-08-17T00:16:25.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.7.0" }
"1.7.1" = { created_at = 2025-08-18T16:32:27.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.7.1" }
"1.8.0" = { created_at = 2025-08-18T20:13:21.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.8.0" }
"1.9.0" = { created_at = 2025-08-19T17:32:05.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.9.0" }
"1.9.1" = { created_at = 2025-08-19T19:13:15.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.9.1" }
"1.9.2" = { created_at = 2025-08-19T20:11:30.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.9.2" }
"1.10.0" = { created_at = 2025-08-22T17:18:47.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.0" }
"1.10.1" = { created_at = 2025-08-22T17:28:34.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.1" }
"1.10.2" = { created_at = 2025-08-22T19:09:06.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.2" }
"1.10.3" = { created_at = 2025-08-24T14:53:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.3" }
"1.10.4" = { created_at = 2025-08-24T16:33:33.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.4" }
"1.10.5" = { created_at = 2025-08-26T13:48:16.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.5" }
"1.10.6" = { created_at = 2025-08-26T14:28:51.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.6" }
"1.10.7" = { created_at = 2025-08-27T20:55:20.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.10.7" }
"1.11.0" = { created_at = 2025-09-06T23:33:54.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.11.0" }
"1.11.1" = { created_at = 2025-09-07T00:07:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.11.1" }
"1.11.2" = { created_at = 2025-09-07T00:35:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.11.2" }
"1.12.0" = { created_at = 2025-09-07T20:34:53.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.12.0" }
"1.12.1" = { created_at = 2025-09-13T15:58:11.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.12.1" }
"1.13.0" = { created_at = 2025-09-17T03:46:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.0" }
"1.13.1" = { created_at = 2025-09-17T03:59:09.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.1" }
"1.13.2" = { created_at = 2025-09-17T04:09:38.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.2" }
"1.13.3" = { created_at = 2025-09-17T04:18:36.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.3" }
"1.13.4" = { created_at = 2025-09-17T04:43:53.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.4" }
"1.13.6" = { created_at = 2025-09-17T12:30:11.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.6" }
"1.13.7" = { created_at = 2025-09-17T12:46:19.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.13.7" }
"1.14.0" = { created_at = 2025-09-18T13:39:43.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.14.0" }
"1.15.0" = { created_at = 2025-09-19T15:27:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.0" }
"1.15.1" = { created_at = 2025-09-19T17:07:42.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.1" }
"1.15.2" = { created_at = 2025-09-20T01:07:42.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.2" }
"1.15.3" = { created_at = 2025-09-21T16:57:09.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.3" }
"1.15.4" = { created_at = 2025-09-22T21:44:51.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.4" }
"1.15.5" = { created_at = 2025-09-22T23:53:28.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.5" }
"1.15.6" = { created_at = 2025-09-25T16:09:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.6" }
"1.15.7" = { created_at = 2025-09-29T00:43:41.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.15.7" }
"1.16.0" = { created_at = 2025-10-02T17:06:01.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.16.0" }
"1.18.0" = { created_at = 2025-10-05T18:32:21.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.18.0" }
"1.18.1" = { created_at = 2025-10-05T20:10:43.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.18.1" }
"1.18.2" = { created_at = 2025-10-07T00:02:11.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.18.2" }
"1.18.3" = { created_at = 2025-10-08T00:12:35.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.18.3" }
"1.19.0" = { created_at = 2025-10-15T15:59:47.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.19.0" }
"1.20.0" = { created_at = 2025-10-29T23:22:25.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.20.0" }
"1.21.0" = { created_at = 2025-11-15T02:21:32.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.21.0" }
"1.21.1" = { created_at = 2025-11-19T17:32:58.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.21.1" }
"1.22.0" = { created_at = 2025-11-19T21:40:13.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.22.0" }
"1.23.0" = { created_at = 2025-11-21T15:07:37.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.23.0" }
"1.24.0" = { created_at = 2025-11-21T23:18:16.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.24.0" }
"1.24.1" = { created_at = 2025-11-22T00:36:15.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.24.1" }
"1.25.0" = { created_at = 2025-11-25T17:26:52.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.25.0" }
"1.26.0" = { created_at = 2025-12-04T15:14:27.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.26.0" }
"1.27.0" = { created_at = 2025-12-12T16:43:38.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.27.0" }
"1.28.0" = { created_at = 2025-12-18T04:33:20.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.28.0" }
"1.29.0" = { created_at = 2026-01-06T19:13:20.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.29.0" }
"1.31.0" = { created_at = 2026-01-19T05:40:06.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.31.0" }
"1.32.0" = { created_at = 2026-01-19T16:21:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.32.0" }
"1.34.0" = { created_at = 2026-01-27T14:42:12.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.34.0" }
"1.35.0" = { created_at = 2026-02-01T11:13:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.35.0" }
"1.36.0" = { created_at = 2026-02-09T03:33:14.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.36.0" }
"1.37.0" = { created_at = 2026-03-03T15:31:51.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.37.0" }
"1.38.0" = { created_at = 2026-03-07T01:22:20.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.38.0" }
"1.39.0" = { created_at = 2026-03-22T19:51:09.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.39.0" }
"1.40.0" = { created_at = 2026-04-01T16:35:03.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.40.0" }
"1.41.0" = { created_at = 2026-04-05T17:35:43.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.41.0" }
"1.41.1" = { created_at = 2026-04-10T01:03:57.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.41.1" }
"1.42.0" = { created_at = 2026-04-12T13:39:51.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.42.0" }
"1.43.0" = { created_at = 2026-04-16T17:13:30.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.43.0" }
"1.44.0" = { created_at = 2026-04-23T17:21:30.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.44.0" }
"1.44.1" = { created_at = 2026-04-24T13:35:08.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.44.1" }
"1.44.2" = { created_at = 2026-04-26T22:56:49.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.44.2" }
"1.44.3" = { created_at = 2026-04-30T16:12:47.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.44.3" }
"1.45.0" = { created_at = 2026-05-05T13:26:24.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.45.0" }
"1.46.0" = { created_at = 2026-05-27T20:46:26.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.46.0" }
"1.47.0" = { created_at = 2026-06-09T08:10:42.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.47.0" }
"1.48.0" = { created_at = 2026-06-11T20:45:23.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.48.0" }
"1.49.0" = { created_at = 2026-07-01T22:53:16.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.49.0" }
"1.50.0" = { created_at = 2026-07-06T21:29:47.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.50.0" }
"1.51.0" = { created_at = 2026-07-14T10:48:40.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.51.0" }
"1.52.0" = { created_at = 2026-07-21T10:57:30.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.52.0" }
"1.53.0" = { created_at = 2026-07-23T17:08:09.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.53.0" }
"1.54.0" = { created_at = 2026-07-31T00:24:01.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.54.0" }
"1.54.1" = { created_at = 2026-08-07T10:33:34.000Z, release_url = "https://github.com/jdx/hk/releases/tag/v1.54.1" }
