[versions]
"1.8.2" = { created_at = 2026-10-05T03:12:26.000Z, release_url = "https://github.com/jdx/jactionlint/releases/tag/v1.8.2" }
"2.0.2" = { created_at = 2026-10-09T19:57:48.000Z, release_url = "https://github.com/jdx/jactionlint/releases/tag/v2.0.2" }
"2.1.0" = { created_at = 2026-10-10T13:59:33.000Z, release_url = "https://github.com/jdx/jactionlint/releases/tag/v2.1.0" }
