[versions]
"0.1.0" = { created_at = 2022-09-19T20:44:19.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.1.0" }
"0.2.0" = { created_at = 2022-09-25T02:36:06.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.2.0" }
"0.3.0" = { created_at = 2022-10-02T21:53:07.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.3.0" }
"0.4.0" = { created_at = 2023-01-07T22:52:04.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.4.0" }
"0.5.0" = { created_at = 2023-09-18T02:05:21.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.5.0" }
"0.6.0" = { created_at = 2024-05-05T20:35:00.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.6.0" }
"0.7.0" = { created_at = 2024-06-09T22:10:49.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.7.0" }
"0.8.0" = { created_at = 2025-09-28T01:10:03.000Z, release_url = "https://github.com/noahgorstein/jqp/releases/tag/v0.8.0" }
