[versions]
"5.3.0-rc.1" = { created_at = 2022-02-03T09:42:38.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.3.0-rc.1", prerelease = true }
"5.3.0" = { created_at = 2022-02-03T12:41:02.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.3.0" }
"5.4.0-dev.2" = { created_at = 2022-03-24T12:02:13.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.0-dev.2", prerelease = true }
"5.4.0-dev.3" = { created_at = 2022-03-24T14:53:56.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.0-dev.3", prerelease = true }
"5.4.0" = { created_at = 2022-03-26T11:07:10.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.0" }
"5.4.1" = { created_at = 2022-03-29T08:58:08.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.1" }
"5.4.2" = { created_at = 2022-06-04T21:44:15.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.2" }
"5.4.3" = { created_at = 2022-06-07T16:59:53.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.3" }
"5.4.4" = { created_at = 2022-07-11T10:12:30.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.4" }
"5.4.6" = { created_at = 2022-08-29T10:08:49.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.6" }
"5.4.7" = { created_at = 2023-02-02T12:58:24.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.7" }
"5.4.8" = { created_at = 2023-03-04T20:29:05.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.8" }
"5.4.9" = { created_at = 2023-03-17T05:33:48.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.4.9" }
"5.5.0" = { created_at = 2023-05-17T15:10:32.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.5.0" }
"5.5.1" = { created_at = 2023-05-19T12:21:59.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.5.1" }
"5.5.2" = { created_at = 2023-08-03T04:47:27.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.5.2" }
"5.6.0" = { created_at = 2023-08-21T11:39:05.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.6.0" }
"5.6.2" = { created_at = 2024-04-09T16:39:15.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.6.2" }
"5.6.3" = { created_at = 2024-04-10T12:15:36.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.6.3" }
"5.7.0" = { created_at = 2024-07-04T12:05:25.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.0" }
"5.7.1" = { created_at = 2024-07-05T14:07:00.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.1" }
"5.7.2" = { created_at = 2024-07-14T16:53:21.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.2" }
"5.7.3" = { created_at = 2024-08-02T10:59:59.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.3" }
"5.7.4" = { created_at = 2024-09-12T09:41:28.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.4" }
"5.7.5" = { created_at = 2024-11-26T14:10:23.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.7.5" }
"5.8.0" = { created_at = 2025-01-17T10:17:35.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.8.0" }
"5.8.1" = { created_at = 2025-01-17T11:10:52.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.8.1" }
"5.8.2" = { created_at = 2025-02-12T10:44:09.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.8.2" }
"5.8.3" = { created_at = 2025-02-15T19:06:00.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.8.3" }
"5.9.0-rc.0" = { created_at = 2025-09-22T20:55:31.000Z, release_url = "https://github.com/k3d-io/k3d/releases/tag/v5.9.0-rc.0", prerelease = true }
