[versions]
"0.1.0" = { created_at = 2026-02-25T07:59:52.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.1.0" }
"0.2.0" = { created_at = 2026-03-04T12:24:57.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.2.0" }
"0.2.1" = { created_at = 2026-03-04T13:08:05.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.2.1" }
"0.2.2" = { created_at = 2026-03-04T13:38:41.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.2.2" }
"0.2.3" = { created_at = 2026-03-04T13:55:53.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.2.3" }
"0.3.0" = { created_at = 2026-03-05T10:03:21.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.3.0" }
"0.3.1" = { created_at = 2026-03-09T13:08:19.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.3.1" }
"0.4.0" = { created_at = 2026-03-11T18:59:44.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.4.0" }
"0.4.1" = { created_at = 2026-03-12T09:26:22.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.4.1" }
"0.5.0" = { created_at = 2026-03-16T15:14:04.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.0" }
"0.5.1" = { created_at = 2026-03-17T13:14:53.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.1" }
"0.5.2" = { created_at = 2026-03-19T15:15:41.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.2" }
"0.5.3" = { created_at = 2026-03-23T07:46:02.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.3" }
"0.5.4" = { created_at = 2026-03-26T11:43:53.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.4" }
"0.5.5" = { created_at = 2026-04-02T10:39:37.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.5" }
"0.5.6" = { created_at = 2026-04-09T10:46:52.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.6" }
"0.5.7" = { created_at = 2026-04-16T10:51:08.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.7" }
"0.5.8" = { created_at = 2026-04-23T10:57:48.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.5.8" }
"0.6.0" = { created_at = 2026-04-30T10:58:16.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.6.0" }
"0.7.0" = { created_at = 2026-05-07T10:59:06.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.7.0" }
"0.7.1" = { created_at = 2026-05-07T12:57:50.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.7.1" }
"0.8.0" = { created_at = 2026-05-14T11:03:29.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2026-05-21T11:21:18.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.9.0" }
"0.10.0" = { created_at = 2026-05-28T11:30:12.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.10.0" }
"0.11.0" = { created_at = 2026-06-04T11:24:37.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.11.0" }
"0.12.0" = { created_at = 2026-06-11T11:53:43.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.12.0" }
"0.13.0" = { created_at = 2026-06-18T11:56:47.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.13.0" }
"0.14.0" = { created_at = 2026-06-25T11:22:49.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.14.0" }
"0.14.1" = { created_at = 2026-06-29T16:43:37.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.14.1" }
"0.15.0" = { created_at = 2026-07-02T11:22:29.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.15.0" }
"0.16.0" = { created_at = 2026-07-09T11:31:11.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.16.0" }
"0.17.0" = { created_at = 2026-07-14T15:13:48.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.17.0" }
"0.17.1" = { created_at = 2026-07-16T11:06:35.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.17.1" }
"0.18.0" = { created_at = 2026-07-23T11:09:22.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.18.0" }
"0.19.0" = { created_at = 2026-07-28T12:58:51.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.19.0" }
"0.20.0" = { created_at = 2026-07-30T11:09:07.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.20.0" }
"0.20.1" = { created_at = 2026-07-30T17:55:11.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.20.1" }
"0.21.0" = { created_at = 2026-08-06T11:22:17.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.21.0" }
"0.22.0" = { created_at = 2026-08-13T10:49:43.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.22.0" }
"0.22.1" = { created_at = 2026-08-20T10:34:01.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.22.1" }
"0.22.2" = { created_at = 2026-08-27T14:00:18.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.22.2" }
"0.23.0" = { created_at = 2026-09-03T10:42:59.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v0.23.0" }
"1.0.0" = { created_at = 2026-09-07T10:50:41.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v1.0.0" }
"1.0.1" = { created_at = 2026-09-10T10:42:33.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v1.0.1" }
"1.1.0" = { created_at = 2026-09-17T10:40:02.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v1.1.0" }
"1.2.0" = { created_at = 2026-09-24T16:31:08.000Z, release_url = "https://github.com/localstack/lstk/releases/tag/v1.2.0" }
