[versions]
"2.10.1" = { created_at = 2024-05-22T16:20:09.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.10.1" }
"2.8.10" = { created_at = 2024-06-05T15:31:02.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.8.10" }
"2.9.7" = { created_at = 2024-06-05T16:31:05.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.9.7" }
"2.10.2" = { created_at = 2024-06-05T17:15:41.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.10.2" }
"2.10.4" = { created_at = 2024-06-18T17:56:50.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.10.4" }
"2.10.6" = { created_at = 2024-07-05T16:57:29.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.10.6" }
"2.10.7" = { created_at = 2024-07-17T14:23:40.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.10.7" }
"2.11.0" = { created_at = 2024-08-07T20:40:47.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.0" }
"2.11.1" = { created_at = 2024-08-21T14:00:56.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.1" }
"2.11.2" = { created_at = 2024-09-04T17:10:27.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.2" }
"2.11.3" = { created_at = 2024-09-18T14:37:20.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.3" }
"2.11.4" = { created_at = 2024-10-07T15:24:45.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.4" }
"2.11.5" = { created_at = 2024-10-16T16:35:11.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.5" }
"2.11.6" = { created_at = 2024-12-13T17:00:49.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.11.6" }
"2.12.2" = { created_at = 2025-01-15T20:37:26.000Z, release_url = "https://github.com/pachyderm/pachyderm/releases/tag/v2.12.2" }
