[versions]
"0.4.0" = { created_at = 2017-06-05T22:07:20.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.4.0" }
"0.4.1" = { created_at = 2017-06-07T15:54:25.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.4.1" }
"0.4.2" = { created_at = 2017-07-17T17:11:32.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.4.2" }
"0.4.5" = { created_at = 2017-11-13T22:01:27.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.4.5" }
"0.6.0" = { created_at = 2017-12-11T18:58:01.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.6.0" }
"0.8.0" = { created_at = 2017-12-14T21:37:40.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2018-01-02T08:39:08.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.9.0" }
"0.11.0" = { created_at = 2018-03-06T17:13:11.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.11.0" }
"0.12.0" = { created_at = 2018-03-06T17:13:40.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.12.0" }
"0.13.0" = { created_at = 2018-03-11T16:02:42.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.13.0" }
"0.13.1" = { created_at = 2018-06-06T20:23:25.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.13.1" }
"0.13.2" = { created_at = 2018-06-11T18:45:35.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.13.2" }
"0.13.3" = { created_at = 2018-06-11T18:57:26.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.13.3" }
"0.13.4" = { created_at = 2018-06-12T16:16:49.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.13.4" }
"0.14.0" = { created_at = 2018-06-17T19:58:56.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.14.0" }
"0.14.1" = { created_at = 2018-06-18T14:01:34.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.14.1" }
"0.14.2" = { created_at = 2018-07-14T16:24:56.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.14.2" }
"0.14.3" = { created_at = 2018-07-15T23:37:52.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.14.3" }
"0.15.3" = { created_at = 2018-07-16T11:15:49.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.3" }
"0.15.4" = { created_at = 2018-09-05T19:14:09.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.4" }
"0.15.5" = { created_at = 2018-09-05T19:19:16.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.5" }
"0.15.6" = { created_at = 2018-09-17T17:53:40.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.6" }
"0.15.7" = { created_at = 2018-09-25T03:15:12.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.7" }
"0.15.8" = { created_at = 2018-09-25T15:13:28.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.15.8" }
"0.16.0" = { created_at = 2018-11-14T15:28:49.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.16.0" }
"0.16.1" = { created_at = 2019-11-20T06:52:34.000Z, release_url = "https://github.com/genuinetools/reg/releases/tag/v0.16.1" }
