[versions]
"3.3.4" = { created_at = 2026-03-25T21:04:38.000Z, release_url = "https://github.com/getsentry/sentry-cli/releases/tag/3.3.4" }
"3.3.5" = { created_at = 2026-03-30T11:10:01.000Z, release_url = "https://github.com/getsentry/sentry-cli/releases/tag/3.3.5" }
"3.4.0" = { created_at = 2026-04-20T11:59:20.000Z, release_url = "https://github.com/getsentry/sentry-cli/releases/tag/3.4.0" }
