[versions]
"4.6.4" = { created_at = 2026-03-31T08:00:31.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.4" }
"4.6.5" = { created_at = 2026-03-31T08:01:23.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.5" }
"4.6.6" = { created_at = 2026-03-31T08:05:05.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.6" }
"4.6.7" = { created_at = 2026-03-31T08:48:12.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.7" }
"4.6.8" = { created_at = 2026-03-31T09:40:51.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.8" }
"4.6.9" = { created_at = 2026-03-31T15:48:40.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.9" }
"4.6.10" = { created_at = 2026-04-02T10:46:34.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.10" }
"4.6.11" = { created_at = 2026-04-02T19:28:01.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.6.11" }
"4.7.0" = { created_at = 2026-04-09T12:16:43.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.0" }
"4.7.1" = { created_at = 2026-04-10T12:05:13.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.1" }
"4.7.2" = { created_at = 2026-04-13T14:39:40.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.2" }
"4.7.3" = { created_at = 2026-04-14T08:30:43.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.3" }
"4.7.4" = { created_at = 2026-04-15T16:48:30.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.4" }
"4.7.5" = { created_at = 2026-04-16T11:39:40.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.5" }
"4.7.6" = { created_at = 2026-04-17T16:51:02.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.6" }
"4.7.7" = { created_at = 2026-04-17T16:59:52.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.7" }
"4.7.8" = { created_at = 2026-04-18T18:20:54.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.8" }
"4.7.9" = { created_at = 2026-04-18T19:08:45.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.7.9" }
"4.8.0" = { created_at = 2026-04-19T13:41:11.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.8.0" }
"4.9.0" = { created_at = 2026-04-20T12:55:12.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.9.0" }
"4.9.1" = { created_at = 2026-04-20T15:12:42.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.9.1" }
"4.9.2" = { created_at = 2026-04-21T11:56:37.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.9.2" }
"4.9.3" = { created_at = 2026-04-21T14:35:16.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.9.3" }
"4.10.0" = { created_at = 2026-04-21T17:37:14.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.10.0" }
"4.10.1" = { created_at = 2026-04-22T15:38:05.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.10.1" }
"4.10.2" = { created_at = 2026-04-23T10:45:50.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.10.2" }
"4.11.0" = { created_at = 2026-04-23T15:43:49.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.11.0" }
"4.12.0" = { created_at = 2026-04-23T16:35:09.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.12.0" }
"4.12.1" = { created_at = 2026-04-24T10:58:43.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.12.1" }
"4.12.2" = { created_at = 2026-04-24T12:41:42.000Z, release_url = "https://github.com/sst/sst/releases/tag/v4.12.2" }
