[versions]
"4.178.0" = { created_at = 2026-04-09T15:17:37.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.178.0" }
"4.178.1" = { created_at = 2026-04-10T07:33:39.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.178.1" }
"4.179.0" = { created_at = 2026-04-10T13:29:31.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.179.0" }
"4.179.1" = { created_at = 2026-04-11T00:52:42.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.179.1" }
"4.179.2" = { created_at = 2026-04-11T11:36:56.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.179.2" }
"4.179.3" = { created_at = 2026-04-11T12:01:03.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.179.3" }
"4.180.0" = { created_at = 2026-04-12T13:18:10.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.180.0" }
"4.181.0" = { created_at = 2026-04-16T17:38:08.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.181.0" }
"4.181.1" = { created_at = 2026-04-17T11:28:03.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.181.1" }
"4.182.0" = { created_at = 2026-04-17T16:16:23.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.182.0" }
"4.182.1" = { created_at = 2026-04-21T10:37:29.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.182.1" }
"4.183.0" = { created_at = 2026-04-21T12:58:18.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.183.0" }
"4.183.1" = { created_at = 2026-04-22T09:31:24.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.183.1" }
"4.184.0" = { created_at = 2026-04-22T17:11:48.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.184.0" }
"4.184.1" = { created_at = 2026-04-22T21:17:49.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.184.1" }
"4.184.2" = { created_at = 2026-04-23T10:06:25.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.184.2" }
"4.185.0" = { created_at = 2026-04-23T15:23:03.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.185.0" }
"4.185.1" = { created_at = 2026-04-23T16:50:36.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.185.1" }
"4.186.0" = { created_at = 2026-04-24T10:30:41.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.186.0" }
"4.186.1" = { created_at = 2026-04-24T11:36:15.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.186.1" }
"4.186.2" = { created_at = 2026-04-24T13:03:35.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.186.2" }
"4.187.0" = { created_at = 2026-04-27T07:51:45.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.187.0" }
"4.188.0" = { created_at = 2026-04-27T09:50:32.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.188.0" }
"4.188.1" = { created_at = 2026-04-27T13:01:10.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.188.1" }
"4.188.2" = { created_at = 2026-04-27T13:33:38.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.188.2" }
"4.188.3" = { created_at = 2026-04-27T16:23:30.000Z, release_url = "https://github.com/tuist/tuist/releases/tag/4.188.3" }
