[versions]
"0.0.1" = { created_at = 2022-10-25T14:18:40.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.0.1" }
"0.1.0" = { created_at = 2022-10-27T12:56:42.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.1.0" }
"0.1.1" = { created_at = 2022-10-28T20:40:06.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.1.1" }
"0.2.0" = { created_at = 2022-11-22T17:23:00.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.2.0" }
"0.3.0" = { created_at = 2023-02-21T18:46:23.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.3.0" }
"0.4.0" = { created_at = 2023-04-05T18:40:38.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.4.0" }
"0.5.0" = { created_at = 2023-05-17T19:08:03.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.5.0" }
"0.6.0" = { created_at = 2023-07-20T19:14:51.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.6.0" }
"0.7.1" = { created_at = 2023-12-12T19:50:53.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.7.1" }
"0.7.2" = { created_at = 2024-04-15T15:12:30.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.7.2" }
"0.8.0" = { created_at = 2024-09-06T17:16:14.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2025-01-15T18:38:25.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.9.0" }
"0.10.0" = { created_at = 2025-06-17T19:17:12.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.10.0" }
"0.11.0" = { created_at = 2026-03-10T18:39:47.000Z, release_url = "https://github.com/charmbracelet/vhs/releases/tag/v0.11.0" }
