name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4
      - run: aube ci
      - run: aube --dir web run build
      - run: aube run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4
      - run: aube ci
      - run: mise run types:check
      - run: hk check
